name: CI image

on:
  workflow_dispatch:
    inputs:
      alias:
        description: 'Docker image alias'
        required: true

jobs:

  build-publish-ci-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: docker/ci/Dockerfile
          tags: |
            ghcr.io/kbujanecki-dt/casskop-build:latest
            ghcr.io/kbujanecki-dt/casskop-build:${{ github.event.inputs.alias }}
          build-args: OPERATOR_SDK_VERSION=v1.13.0
          push: true
